package com.oculussoftware.api.repi;

import com.oculussoftware.util.*;

/** An  enumeration.
*/
public class AttributeKind extends IntEnum
{
  public static final AttributeKind CUSTOM   = new AttributeKind(1);
  public static final AttributeKind STANDARD   = new AttributeKind(2);
  public static final AttributeKind AGGREGATE = new AttributeKind(3);
  public static final AttributeKind ALL = new AttributeKind(4);
  public static final AttributeKind QUESTION = new AttributeKind(5);
  public static final AttributeKind PRODENUM = new AttributeKind(6);
  public static final AttributeKind SYSTEM_GENERATED = new AttributeKind(7);
  public static final AttributeKind CANNED = new AttributeKind(8);
  public static final AttributeKind IMPORTED = new AttributeKind(9);
  
  
  private AttributeKind(int i)
  {
    super(i);
  }
  
   public static AttributeKind getInstance(int i)
	{
		AttributeKind prim = null;
		switch (i)
		{
			case 1:prim=AttributeKind.CUSTOM;break;
			case 2:prim=AttributeKind.STANDARD;break;
			case 3:prim=AttributeKind.AGGREGATE;break;
			case 4:prim=AttributeKind.ALL;break;
      case 5:prim=AttributeKind.QUESTION;break;
      case 6:prim=AttributeKind.PRODENUM;break;
      case 9:prim=AttributeKind.IMPORTED;break;
      
      
      //Values like Creation date & Created by generated by the system
      //they do not show up on the edit & create forms. But act like
      //other attributes in terms of viewing & moving them around on the form.
      case 7:prim=AttributeKind.SYSTEM_GENERATED;break;
      
      //Canned attributes are those which are stored in the entity table itself
      //example feature priority is attached to the feature table. Canned atributes
      //are not saved using BMProperty
      case 8:prim=AttributeKind.CANNED;break;
			
	  }
	  
	  return prim;
	}
     
  public String toString()
  {
    
    
   String s = null;
    int i = getIntValue();
    switch (i)
    {
      case 1:s="Custom";break;      
      case 2: s="Standard";break;      
      case 3:s="Aggregate";break;      
      case 4:s="Question";break;      
      case 5:s="Question";break;      
      case 6:s="Custom";break;      
      case 7:s="System Generated ";break;      
      case 8:s="Standard ";break;      
      case 9:s="Computed";break;      
    }
  return s; 
    
    
  }   
      
}